### ISSUE TITLE
YNH GitlabRunner fails on "Cannot connect to the Docker daemon"

### ISSUE THREAD

**Issue by colmoneill** [YunoHost-Apps/gitlab-runner_ynh#104]
### Describe the bug

YNH GitlabRunner fails on "Cannot connect to the Docker daemon"

### Context

- Hardware: VPS
- YunoHost version: 11.2.10.3
- I have access to my server: Through SSH | through the webadmin 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### Steps to reproduce

- created a gitlab-runner via the YNH GUI and entered the token provided by the project
- self-hosted gitlab (on another machine) registered the runner
- enabled the runner for that project
- ran the CI pipeline
- pipeline failed with the following errors:
```
ERROR: Failed to remove network for build
ERROR: Preparation failed: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running? (docker.go:933:0s)
```
- full output: https://paste.yunohost.org/idosirihim.sql

### Expected behavior

- Runner should pick up the task and execute, in this case it involves an `npm install` and an `npx` command execution (11ty process) 
- CI file is here: https://git.materialsmatter.ie/colm/wilderland.ie/-/blob/main/.gitlab-ci.yml?ref_type=heads

### Logs

app installation logs: https://paste.yunohost.org/raw/fihagicewo

Thank you for any help you can provide!

Best regards,

**Comment by colmoneill** [comment]
This line in the install log caught my eye, because it is the same message as my gitlab-ci error :

```
2024-04-04 09:05:47,429: WARNING - Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

So my belief is that 'gitlab-runner_ynh' was not starting the docker process (in my case anyway). I ran this command and my pipeline worked, resolving the issue:

```
sudo service docker restart
```

https://paste.yunohost.org/mezanavose.yaml

Hope this helps

**Comment by kay0u** [comment]
Thanks for the report and your help on matrix to find out what the problem was, I tried to solve it by starting the docker service if it's not before installing gitlab-runner.

Let's wait the CI: https://github.com/YunoHost-Apps/gitlab-runner_ynh/pull/105/
