### ISSUE TITLE
Unable to install Gitlab Runner- 'Corrupt Source' error

### ISSUE THREAD

**Issue by ghost** [YunoHost-Apps/gitlab-runner_ynh#32]
### Describe the bug

Gitlab Runner app is unable to install through the Yunohost Admin panel.  During the process, it has a 'Corrupt Source' error and the installation fails with a 'Unable to install gitlab-runner: An error occurred inside the app installation script'.  

### Context

- Hardware: Windows PC x64 running Yunohost through Hyper-V- everything, including other apps seem to be performing fine.
- Latest YunoHost version

### Steps to reproduce

Add GitLab runner credentials provided in Gitlab.com repo
URL: https://gitlab.com/
Registration Token: secret-token

Attempted install with the default 'alpine:latest' image as well as 'node:latest'

Proceed with install, fails about halfway through.  

### Expected behavior

I expect the runner to install

### Logs

https://paste.yunohost.org/raw/julakikeqo

**Comment by Karalix** [comment]
I am seing the exact same problem on a dedicated VPS, using up to date system and yunohost packages : https://paste.yunohost.org/raw/supuvelasi

If I retry after the first failure, it says it had a problem while processing docker-ce : https://paste.yunohost.org/raw/iyeqacidus

**Comment by markfoodyburton** [comment]
The solution to this problem :
```
2021-07-01 09:02:55,517: DEBUG -   Process: 9854 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, status=1/FAILURE)
```
is given here : 
https://forums.docker.com/t/failed-to-load-listeners-no-sockets-found-via-socket-activation-make-sure-the-service-was-started-by-systemd/62505
(I personally got past this by fixing the system file and then allowing Juno to re-install, I dont know if thats a good approach)

However, that doesn't fix the corrupt package issue.

**Comment by markfoodyburton** [comment]
see https://github.com/YunoHost-Apps/gitlab-runner_ynh/pull/33
