### ISSUE TITLE
Dependencies already being installed causes entire script to abort

### ISSUE THREAD

**Issue by haydenwalker980** [YunoHost-Apps/gitlab-runner_ynh#36]
### Describe the bug

When dependencies are already installed Yunohost treats it as if apt errored and subsequently says the script fails.

### Context

- Hardware: Linode 8GB Dedicated
- YunoHost version: 4.3.6.2
- I have access to my server: SSH, webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: No
- Using, or trying to install package version/branch: Latest, stable

### Steps to reproduce

Webadmin was used, although I tried in CLI and it fails there too
Reproduction steps:
* First install docker and containerd.io
* Next attempt an installation of gitlab-runner via webadmin or CLI.
* Enjoy your error.

### Expected behavior

Expected: YunoHost skips dependency installation because dependencies are installed already.

### Logs
https://paste.yunohost.org/raw/ufuvupajoy

**Comment by julientaq** [comment]
Hi there, i have the exact same issue.
Is there any work around?

Thanks!

**Comment by julientaq** [comment]
This is my complete log.
https://paste.yunohost.org/raw/jamajesaqu

**Comment by yalh76** [comment]
The issue comes from you already have docker install but gitlab-runner_ynh needs to install docker-ce. And as described in the documentation, https://docs.docker.com/engine/install/debian/#uninstall-old-versions, `Older versions of Docker were called docker, docker.io, or docker-engine. If these are installed, uninstall them:`

**Comment by julientaq** [comment]
Thanks for your answer :)
