### ISSUE TITLE
[Freebox Delta] Wrong architecture 

### ISSUE THREAD

**Issue by eagleofdeath13** [YunoHost-Apps/gitlab-runner_ynh#38]
### Describe the bug

While installing gitlab-runner, the installation fail, picking the wrong architecture (AMD64 instead of ARM64).

### Context

Hardware : Freebox Delta, with Yunohost installed from a clean Debian. 8G of RAM instead of original 2.
YunoHost version : 4.3.6.3
Acessed via WebUI
No particular tweaking except manual install of Yunohost (no premade image for this hardware)
Gitlab-runner version 15.0.0~ynh1

### Steps to reproduce

Classic install from WebUI on this hardware

### Expected behavior

The right architecture is detected and used to install the app.

### Logs

https://paste.yunohost.org/raw/julahutuho

**Comment by yalh76** [comment]
You should retry, was fixed at https://github.com/YunoHost-Apps/gitlab-runner_ynh/pull/40
